version: "3"
services:
  http_mock:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=info
      - FASTIFY_PRETTY_LOGS=false
    command: bash -c "npx fastify start src/httpmock.js --watch"
  adapter:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - SMAUG_URL=http://http_mock:3000/smaug/configuration
      - PUBLIZON_URL=http://http_mock:3000/publizon
      - USERINFO_URL=http://http_mock:3000/userinfo
      - AUTH_URL=http://http_mock:3000/auth
      - CLIENT_ID=some-client-id
      - CLIENT_SECRET=some-client-secret
      - CORS_ORIGIN=all
    depends_on:
      - http_mock
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:latest
    volumes:
      - "./e2e:/app/e2e"
    depends_on:
      - adapter
      - http_mock
    environment:
      - CYPRESS_baseUrl=http://adapter:3000
      - CYPRESS_mockHTTPUrl=http://http_mock:3000
    command: bash -c "npm run cy"
