version: "3"
services:
  http_mock:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=info
      - FASTIFY_PRETTY_LOGS=false
    command: bash -c "npx fastify start src/httpmock.js --watch"
  adapter:
    image: "${IMAGE}"
    environment:
      - APP_NAME=Adapter
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - CORS_ORIGIN=all

      - PUBLIZON_URL=http://http_mock:3000/publizon
      - PUBLIZON_CLIENT_ID=some-clientId
      - SMAUG_URL=http://http_mock:3000/smaug/configuration
      - USERINFO_URL=http://http_mock:3000/userinfo

      - |
        PUBLIZON_CREDENTIALS=
        000001,d4383a9fa7214a6d78a019c1328695a3,some-retailerId
        000002,d4383a9fa7214a6d78a019c1328695a3,some-retailerId
        000003,
        000004,d4383a9fa7214a6d78a019c1328695a3
        000005,,some-retailerId,
        ${VALID_PUBLIZON_CREDENTIALS}

    depends_on:
      - http_mock
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:old-202409
    volumes:
      - "./e2e:/app/e2e"
    depends_on:
      - adapter
      - http_mock
    environment:
      - CYPRESS_baseUrl=http://adapter:3000
      - CYPRESS_mockHTTPUrl=http://http_mock:3000
    command: bash -c "npm run cy"
