version: "3"
services:
  http_mock:
    build: .
    environment:
      - FASTIFY_LOG_LEVEL=error
      - FASTIFY_PRETTY_LOGS=false
    volumes:
      - "./src:/home/node/app/src"
    command: bash -c "npx fastify-cli start src/httpmock.js --watch"
    ports:
      - "3333:3000"
  adapter:
    build: .
    environment:
      - APP_NAME=Adapter
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - CORS_ORIGIN=all

      # - PUBLIZON_URL=http://http_mock:3000/publizon
      # - PUBLIZON_CLIENT_ID=some-clientId
      # - SMAUG_URL=http://http_mock:3000/smaug/configuration
      # - USERINFO_URL=http://http_mock:3000/userinfo

      - PUBLIZON_URL=https://library-api.qa.pubhub.dk
      # - PUBLIZON_URL=https://library-api.pubhub.dk

      - PUBLIZON_CLIENT_ID=${PUBLIZON_CLIENT_ID}
      - SMAUG_URL=https://auth-config.dbc.dk/configuration
      - USERINFO_URL=https://login.bib.dk/userinfo

      - |
        PUBLIZON_CREDENTIALS=
        000001,some-licenseKey,some-retailerId
        000002,some-licenseKey,some-retailerId
        000003,
        000004,some-licenseKey
        000005,,some-retailerId,
        ${VALID_PUBLIZON_CREDENTIALS}

    ports:
      - "3000:3000"
    volumes:
      - "./src:/home/node/app/src"
    depends_on:
      - http_mock
    command: bash -c "npx fastify-cli start src/server.js --watch"
